image: docker:latest
services:
  - docker:dind

stages:
  - build_tags

before_script:
  - echo Logging in to $CI_REGISTRY...
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker info | grep Registry
  - apk add openssh-client git
  - mkdir -p $HOME/.ssh
  - chmod 700 $HOME/.ssh
  - echo $CI_SSH_KEY | base64 -d - > $HOME/.ssh/id_rsa
  - chmod 600 $HOME/.ssh/id_rsa
  - git config --global user.email "marvinroman@protonmail.com"
  - git config --global user.name "Gitlab Runner"

build_tags:
  stage: build_tags
  script:
    - echo Build started on `date` for $CI_COMMIT_TAG
    - sed -i -E "s#/badges/[0-9.]+/pipeline.svg#/badges/${CI_COMMIT_TAG}/pipeline.svg#g" README.md
    - sed -i -E "s#/allume/commits/[0-9.]+#allume/commits/${CI_COMMIT_TAG}#g" README.md
    - git commit README.md -m 'updating pipeline badge'
    - git remote add pipeline git@gitlab.com:mr-coding-challenge/allume.git
    - git push pipeline master
    - docker build -t $CI_REGISTRY_USER/allume_app:$CI_COMMIT_TAG .
    - docker tag  $CI_REGISTRY_USER/allume_app:$CI_COMMIT_TAG $CI_REGISTRY_USER/allume_app:latest
    - docker push $CI_REGISTRY_USER/allume_app:$CI_COMMIT_TAG
    - docker build -t $CI_REGISTRY_USER/allume_tests:$CI_COMMIT_TAG ./tests
    - docker tag  $CI_REGISTRY_USER/allume_tests:$CI_COMMIT_TAG $CI_REGISTRY_USER/allume_tests:latest
    - docker push $CI_REGISTRY_USER/allume_tests:$CI_COMMIT_TAG

  only:
    - /^[0-9.]+$/
